version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik_proxy
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - webproxy

  control-plane:
    build:
      context: ./control-plane
    container_name: saas_control_plane
    volumes:
      - ./saas_sites:/var/saas_sites
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=production
      - SITES_PATH=/var/saas_sites
    networks:
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.control-plane.rule=Host(`manage.yourdomain.com`)"
      - "traefik.http.routers.control-plane.entrypoints=websecure"
      - "traefik.http.routers.control-plane.tls.certresolver=myresolver"
      - "traefik.http.services.control-plane.loadbalancer.server.port=5001"

networks:
  webproxy:
    name: webproxy
    driver: bridge
